### PR TITLE
Feature/delete group form

### PR DESCRIPTION
**Pull request by BowenAnna**
Delete group functionality working and will delete group from the nav bar list and local storage.
I had some trouble with CreateGroup.jsx, not sure why. I checked it and it looks the same as the one in the dev branch.

### CODE REVIEW

**Comment by Satomili** [comment]
Looks good, It is working perfectly.

**Comment by BowenAnna** [comment]
Per Satomi, everything looks good, going to merge it to the dev branch

**Review by Satomili — COMMENTED** [review]
Looks good

**Review by Satomili — APPROVED** [review]
Looks good

**Pull request merged**
